xpath_expressions:
  news_list:
    site: https://larepublica.co
    links: //h2[@class="headline"]/a/@href
  news_detail:
    title: //h1[@class="headline"]/a/text()
    summary: //div[@class="lead"]/p/text()
    body_paragraphs: //div[@class="articleWrapper  "]/p[not(@class)]/text()